# Verticle Configurations
verticles:
    my_verticle_steve:
        name: "my verticle steve"
        path: "verticles/vert1/vert1.js"
        worker: false
        instances: 1
        isolationGroup:
        isolatedClasses:
        config:
            value1: "dog"
            value2: "cat"